site_name: TODO4NFDI Documentation
site_dir: /tmp/todo4nfdi-doc
site_url: https://base4nfdi.github.io/website-template-mkdocs
docs_dir: ../content
repo_url: https://github.com/base4nfdi/website-template-mkdocs
repo_name: "Base4NFDI mkdocs template"
edit_uri_template: '-/edit/main/{path}'

extra_css:
    - stylesheets/extra.css
theme:
    name: material
    hightlightjs: true
    navigation_depth: 2
    logo: images/logo.png
    font:
      text: Fira Sans
      code: Roboto Mono
      icon: 'mdi'
    custom_dir: ../overrides/
    favicon: images/favicon-32x32.png 
    features:
        #- navigation.tabs
        #- navigation.tabs.sticky
        - navigation.instant
        #- navigation.tracking
        #- navigation.indexes
        #- navigation.top
        - toc.integrate
        - search.suggest
        - content.action.edit
    palette:
        - scheme: default
          toggle:
            icon: material/lightbulb
            name: Switch to dark mode
        - scheme: slate
          toggle:
            icon: material/lightbulb-outline
            name: Switch to light mode

extra:
    generator: false
    social:
      - icon: fontawesome/brands/github
        link: https://github.com/base4nfdi/website-template-mkdocs
    # social:
    #   - icon: images/cc-by-sa_icon.png
    #     link: https://codebase.helmholtz.cloud/m-team/nfdi/nfdi-aai-doc/
    footer:
      copyright: "&copy 2024 TODO4NFDI, <a href='https://base4nfdi.de/'>Base4NFDI</a>"
      lines: 
          - "Partially funded by DFG as part of NFDI."
          - "Grant Number 521466146"
      links: # can be relative or absolute. Relative links will be prepended the site_url value
          - name: Contact
            link: /contact/
          - name: Imprint
            link: /imprint/
          - name: Privacy Policy
            link: /privacy/
          - name: Accessibility
            link: /accessibility/
      license:
          description: This documentation is licensed under CC BY-SA 4.0
          link: https://creativecommons.org/licenses/by-sa/4.0/legalcode
          logo: images/cc-by-sa_icon.png

markdown_extensions:
    - smarty
    - toc:
          baselevel: 1
          permalink: "#"
          toc_depth: 3
    - admonition
    - def_list
    - pymdownx.details
    - pymdownx.superfences
    - attr_list
    - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
    - pymdownx.superfences
    - pymdownx.tabbed:
        alternate_style: true

plugins:
    - exclude:
          glob:
              - googledocs/*
    - search
    - awesome-pages
    # - git-revision-date-localized
    - macros:
        include_dir: ../include
        module_name: ../include/main
nav:
    - Overview: index.md
    - About: about.md
    - News: news.md
    - Publications: publications.md
    - Docs: docs.md
    - Events: events.md
    - People: people.md
    - Contact: contact.md

not_in_nav: |
  accessibility.md
  imprint.md
  privacy.md

validation: #recommended mkdocs validation settings 
  omitted_files: warn 
  absolute_links: warn 
  unrecognized_links: warn 
  anchors: warn
